[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run serp_volatility/dashboard/app.py --server.port=$PORT --server.headless=true --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false"
