"""
Curated Indian Landmark Cases — sourced from publicly available Supreme Court
and High Court judgment summaries (sci.gov.in, ecourts.gov.in, data.gov.in).

These are well-documented landmark cases that are part of public legal knowledge,
taught in law schools across India, and freely available from government websites.
"""

from datetime import date

INDIAN_LANDMARK_CASES = [
    # ── Constitutional / Fundamental Rights ────────────────────────
    {
        "case_name": "Maneka Gandhi v. Union of India",
        "case_number": "AIR 1978 SC 597",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1978,
        "date_decided": date(1978, 1, 25),
        "jurisdiction": "India",
        "judges": "Justice P.N. Bhagwati, Justice Y.V. Chandrachud, 7-judge bench",
        "petitioner": "Maneka Gandhi",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Expanded the scope of Article 21 (Right to Life and Personal Liberty) beyond mere animal existence to include the right to live with dignity. Established that any law depriving personal liberty must be just, fair, and reasonable — not merely following a procedure.",
        "facts": "Maneka Gandhi's passport was impounded by the government without giving reasons or an opportunity to be heard. She challenged this under Articles 14, 19, and 21 of the Constitution.",
        "issues": "Does the right to travel abroad fall under Article 21? Must the procedure established by law be fair and reasonable?",
        "legal_reasoning": "The Court held that Articles 14, 19, and 21 are not watertight compartments — they are interconnected. Any law affecting personal liberty under Article 21 must also satisfy Article 14 (equality) and Article 19 (freedoms). The 'procedure established by law' must be right, just, and fair, not arbitrary, fanciful, or oppressive.",
        "key_principles": "Expanded interpretation of Article 21; Due process through Article 21; Interconnection of fundamental rights (Articles 14, 19, 21); Right to travel abroad as part of personal liberty; Procedure must be fair, just, and reasonable",
        "statutes_referenced": "Constitution of India — Articles 14, 19, 21; Passports Act 1967, Section 10(3)(c)",
        "precedents_cited": "A.K. Gopalan v. State of Madras (1950) — distinguished/overruled; Satwant Singh v. Passport Officer (1967)",
        "impact": "Transformed Indian constitutional jurisprudence. Made Article 21 the most powerful fundamental right. Led to recognition of right to education, right to privacy, right to clean environment, and dozens of other rights under Article 21.",
        "tags": "constitutional,fundamental rights,article 21,right to life,due process,personal liberty,passport,indian law,landmark",
    },
    {
        "case_name": "Golaknath v. State of Punjab",
        "case_number": "AIR 1967 SC 1643",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1967,
        "date_decided": date(1967, 2, 27),
        "jurisdiction": "India",
        "judges": "Chief Justice K. Subba Rao, 11-judge bench; 6-5 decision",
        "petitioner": "I.C. Golaknath & Others",
        "respondent": "State of Punjab",
        "outcome": "favor",
        "summary": "Held that Parliament cannot amend fundamental rights guaranteed under Part III of the Constitution. Fundamental rights are transcendental and immutable.",
        "facts": "The Golaknath family's surplus land was taken under Punjab land reform laws. They challenged the constitutional amendments that placed land reform laws beyond judicial review.",
        "issues": "Can Parliament amend fundamental rights under Article 368? Are fundamental rights beyond the amending power?",
        "legal_reasoning": "The majority applied the doctrine of prospective overruling and held that fundamental rights cannot be taken away or abridged by constitutional amendments. Article 368 only provides the procedure for amendment, not the power to amend fundamental rights.",
        "key_principles": "Fundamental rights are unamendable; Doctrine of prospective overruling; Article 368 is procedural not substantive; Fundamental rights are transcendental",
        "statutes_referenced": "Constitution of India — Articles 13, 368, Part III; 1st, 4th, 17th Constitutional Amendments",
        "precedents_cited": "Shankari Prasad v. Union of India (1951); Sajjan Singh v. State of Rajasthan (1965) — overruled",
        "impact": "Led directly to the 24th Constitutional Amendment and the Kesavananda Bharati case. Started the great constitutional debate on Parliament's amending power.",
        "tags": "constitutional,amendment power,fundamental rights,land reform,indian law,landmark",
    },
    {
        "case_name": "S.R. Bommai v. Union of India",
        "case_number": "AIR 1994 SC 1918",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1994,
        "date_decided": date(1994, 3, 11),
        "jurisdiction": "India",
        "judges": "9-judge bench; Justice Ahmadi, Justice Jeevan Reddy, Justice Agrawal",
        "petitioner": "S.R. Bommai",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Landmark judgment on the scope of President's Rule under Article 356. Held that secularism is a basic feature of the Constitution, and the power to impose President's Rule is subject to judicial review.",
        "facts": "The central government dismissed several state governments using Article 356 (President's Rule) on grounds of inability to govern per the Constitution. S.R. Bommai, former CM of Karnataka, challenged his government's dismissal.",
        "issues": "Is the exercise of power under Article 356 subject to judicial review? What are the grounds for imposing President's Rule?",
        "legal_reasoning": "The Court held that the President's satisfaction under Article 356 is not absolute and is subject to judicial review. Secularism is part of the basic structure. A state government cannot be dismissed merely because it has lost majority — the test must be on the floor of the Assembly.",
        "key_principles": "Judicial review of Article 356; Secularism is basic structure; Floor test to prove majority; President's Rule cannot be imposed arbitrarily; Federalism as basic structure",
        "statutes_referenced": "Constitution of India — Articles 356, 365; Basic Structure Doctrine",
        "precedents_cited": "Kesavananda Bharati v. State of Kerala (1973); State of Rajasthan v. Union of India (1977)",
        "impact": "Drastically reduced misuse of Article 356 for political purposes. Established clear guidelines for President's Rule. Reinforced secularism and federalism as basic structure features.",
        "tags": "constitutional,president's rule,article 356,secularism,federalism,basic structure,judicial review,indian law,landmark",
    },
    {
        "case_name": "K.S. Puttaswamy v. Union of India (Right to Privacy)",
        "case_number": "(2017) 10 SCC 1",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 2017,
        "date_decided": date(2017, 8, 24),
        "jurisdiction": "India",
        "judges": "9-judge bench; Chief Justice Khehar, Justices Chandrachud, Kaul, Chelameshwar, Bobde, Nariman, Sapre, Abhay Manohar Sapre (unanimous)",
        "petitioner": "Justice K.S. Puttaswamy (Retd.)",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Unanimously declared that the right to privacy is a fundamental right protected under Article 21 of the Constitution. Overruled M.P. Sharma and Kharak Singh which had held that privacy is not a fundamental right.",
        "facts": "Retired Justice Puttaswamy challenged the Aadhaar scheme arguing it violated the right to privacy. The government argued that there is no fundamental right to privacy in the Indian Constitution, relying on M.P. Sharma (1954) and Kharak Singh (1962).",
        "issues": "Is the right to privacy a fundamental right under the Indian Constitution?",
        "legal_reasoning": "Justice Chandrachud held that privacy is intrinsic to life and liberty under Article 21 and is an integral part of freedoms under Article 19. Privacy includes informational privacy, bodily integrity, autonomy of personal choices, and protection of personal information. Any restriction must meet the three-fold test: legality, legitimate aim, and proportionality.",
        "key_principles": "Privacy is a fundamental right under Article 21; Informational privacy; Bodily integrity and autonomy; Three-fold proportionality test for privacy restrictions; Data protection as a constitutional imperative",
        "statutes_referenced": "Constitution of India — Articles 14, 19, 21; Aadhaar Act 2016",
        "precedents_cited": "M.P. Sharma v. Satish Chandra (1954) — overruled; Kharak Singh v. State of UP (1962) — overruled; Maneka Gandhi v. Union of India (1978); Gobind v. State of MP (1975)",
        "impact": "Foundation for India's data protection law (Digital Personal Data Protection Act, 2023). Impacts surveillance, bodily autonomy, sexual orientation rights, and digital rights. One of the most important Indian constitutional decisions of the 21st century.",
        "tags": "constitutional,privacy,fundamental rights,article 21,aadhaar,data protection,digital rights,indian law,landmark",
    },
    {
        "case_name": "Navtej Singh Johar v. Union of India",
        "case_number": "AIR 2018 SC 4321",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 2018,
        "date_decided": date(2018, 9, 6),
        "jurisdiction": "India",
        "judges": "Chief Justice Dipak Misra, Justices Khanwilkar, Chandrachud, Nariman, Malhotra; 5-judge bench (unanimous)",
        "petitioner": "Navtej Singh Johar",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Decriminalized consensual homosexual acts by striking down Section 377 of the Indian Penal Code (insofar as it criminalized consensual sexual conduct between adults). A historic victory for LGBTQ+ rights in India.",
        "facts": "Five petitioners challenged Section 377 IPC which criminalized 'unnatural offences' including consensual homosexual acts. The Supreme Court had earlier upheld Section 377 in Suresh Kumar Koushal (2013).",
        "issues": "Does Section 377 IPC, insofar as it criminalizes consensual sexual acts between adults, violate Articles 14, 15, 19, and 21?",
        "legal_reasoning": "The Court held that sexual orientation is an intrinsic part of identity protected under Article 21. Section 377 discriminated based on sexual orientation, violating Article 14. Criminalizing consensual acts between adults was manifestly arbitrary. The Constitution recognizes and protects the right to sexuality, sexual autonomy, and choice of partner.",
        "key_principles": "Sexual orientation is protected under Article 21; Consensual adult sexual conduct cannot be criminalized; Section 377 struck down as manifestly arbitrary; Constitutional morality over social morality; LGBTQ+ persons have equal citizenship rights",
        "statutes_referenced": "Indian Penal Code, Section 377 — struck down (partially); Constitution of India — Articles 14, 15, 19, 21",
        "precedents_cited": "K.S. Puttaswamy v. Union of India (2017); Naz Foundation v. Govt. of NCT Delhi (2009); Suresh Kumar Koushal v. Naz Foundation (2013) — overruled",
        "impact": "Decriminalized homosexuality in India. A watershed moment for LGBTQ+ rights. Established constitutional morality as the guiding standard over popular morality.",
        "tags": "constitutional,lgbtq rights,section 377,privacy,equality,article 21,article 14,indian law,landmark",
    },
    # ── Criminal Law ───────────────────────────────────────────────
    {
        "case_name": "K.M. Nanavati v. State of Maharashtra",
        "case_number": "AIR 1962 SC 605",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Criminal",
        "year": 1962,
        "date_decided": date(1962, 11, 24),
        "jurisdiction": "India",
        "judges": "Justice Subba Rao, Justice Shah, Justice Ayyangar",
        "petitioner": "Kawas Manekshaw Nanavati",
        "respondent": "State of Maharashtra",
        "outcome": "against",
        "summary": "Famous murder case that was the last jury trial in India. Naval Commander Nanavati shot his wife's lover. The jury acquitted him, but the High Court and Supreme Court overturned the acquittal, leading to India abolishing the jury system.",
        "facts": "Commander Nanavati, a naval officer, discovered his wife's affair with Prem Ahuja. He went to the naval base, took a revolver, drove to Ahuja's home, and shot him dead. The jury acquitted him in a controversial verdict influenced by public sympathy.",
        "issues": "Was the killing premeditated murder or committed in the heat of passion (culpable homicide)? Was the jury verdict perverse?",
        "legal_reasoning": "The Supreme Court held that the time gap between learning of the affair and the shooting was sufficient for premeditation. Nanavati drove to the base, got the revolver, and then drove to Ahuja's house — this was not a sudden act of passion. The jury's acquittal was perverse.",
        "key_principles": "Distinction between murder and culpable homicide; Premeditation vs. sudden provocation; Grave and sudden provocation defense requirements; Jury verdicts can be overturned if perverse",
        "statutes_referenced": "Indian Penal Code — Sections 300, 302 (Murder), 304 (Culpable Homicide); Code of Criminal Procedure",
        "precedents_cited": "Common law principles on provocation defense",
        "impact": "Led to the abolition of jury trials in India (Code of Criminal Procedure Amendment, 1973). One of the most famous criminal cases in Indian legal history.",
        "tags": "criminal,murder,jury trial,provocation,indian law,landmark",
    },
    {
        "case_name": "Hussainara Khatoon v. Home Secretary, State of Bihar",
        "case_number": "AIR 1979 SC 1369",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Criminal",
        "year": 1979,
        "date_decided": date(1979, 3, 9),
        "jurisdiction": "India",
        "judges": "Justice P.N. Bhagwati",
        "petitioner": "Hussainara Khatoon & Others",
        "respondent": "Home Secretary, State of Bihar",
        "outcome": "favor",
        "summary": "Recognized the right to speedy trial as a fundamental right under Article 21. Thousands of undertrial prisoners in Bihar had been in jail longer than the maximum sentence for their alleged offenses. The Court ordered their immediate release.",
        "facts": "An investigative report revealed that thousands of undertrial prisoners in Bihar jails had been incarcerated for periods longer than the maximum punishment for the offenses they were charged with. Many had spent years in jail for bailable offenses.",
        "issues": "Is the right to a speedy trial a fundamental right? Can undertrial prisoners be detained beyond the maximum sentence period?",
        "legal_reasoning": "Justice Bhagwati held that the right to speedy trial flows from Article 21. Procedure which keeps people in jail for long periods without trial is not reasonable, fair, or just. The right to free legal aid is also implicit in Article 21 for those who cannot afford a lawyer.",
        "key_principles": "Right to speedy trial under Article 21; Right to free legal aid as fundamental right; Undertrial detention cannot exceed maximum sentence; State obligation to provide legal aid to poor accused",
        "statutes_referenced": "Constitution of India — Article 21, Article 39A; Code of Criminal Procedure — Section 167",
        "precedents_cited": "Maneka Gandhi v. Union of India (1978)",
        "impact": "Led to massive prison reforms in India. Thousands of undertrial prisoners were released. Paved the way for the Legal Services Authorities Act, 1987. Established free legal aid as a constitutional right.",
        "tags": "criminal,speedy trial,undertrial prisoners,legal aid,article 21,prison reform,indian law,landmark",
    },
    {
        "case_name": "Bachan Singh v. State of Punjab",
        "case_number": "AIR 1980 SC 898",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Criminal",
        "year": 1980,
        "date_decided": date(1980, 5, 9),
        "jurisdiction": "India",
        "judges": "Justice Y.V. Chandrachud (majority); Justice P.N. Bhagwati (dissent); 5-judge bench; 4-1 decision",
        "petitioner": "Bachan Singh",
        "respondent": "State of Punjab",
        "outcome": "against",
        "summary": "Upheld the constitutionality of the death penalty in India but established the 'rarest of rare' doctrine — death sentence should only be imposed in the rarest of rare cases when the alternative of life imprisonment is unquestionably foreclosed.",
        "facts": "Bachan Singh challenged the constitutional validity of the death penalty under Section 302 of the Indian Penal Code, arguing it violated Articles 14, 19, and 21.",
        "issues": "Is the death penalty constitutional? Under what circumstances can it be imposed?",
        "legal_reasoning": "The majority upheld the death penalty as constitutional but created strict guidelines. Death can be imposed only in 'rarest of rare' cases. Courts must consider both aggravating and mitigating circumstances. The balance should tilt toward life imprisonment — death only when life imprisonment is inadequate.",
        "key_principles": "Rarest of rare doctrine for death penalty; Death penalty is constitutional but exceptional; Courts must weigh aggravating vs. mitigating factors; Life imprisonment is the rule, death the exception; Both crime and criminal must be considered",
        "statutes_referenced": "Indian Penal Code — Section 302 (Murder); Constitution of India — Articles 14, 19, 21; CrPC Section 354(3)",
        "precedents_cited": "Jagmohan Singh v. State of UP (1973); Rajendra Prasad v. State of UP (1979)",
        "impact": "Definitive ruling on death penalty in India. The 'rarest of rare' standard continues to guide all death penalty decisions. Frequently cited in capital punishment jurisprudence worldwide.",
        "tags": "criminal,death penalty,rarest of rare,capital punishment,article 21,sentencing,indian law,landmark",
    },
    {
        "case_name": "D.K. Basu v. State of West Bengal",
        "case_number": "AIR 1997 SC 610",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Criminal",
        "year": 1997,
        "date_decided": date(1997, 1, 18),
        "jurisdiction": "India",
        "judges": "Justice A.S. Anand, Justice Kuldip Singh",
        "petitioner": "D.K. Basu (Executive Chairman, Legal Aid Services, West Bengal)",
        "respondent": "State of West Bengal",
        "outcome": "favor",
        "summary": "Laid down binding guidelines to prevent custodial torture and deaths. Established requirements for arrest procedures including memo of arrest, informing relatives, medical examination, and right to legal counsel. Custodial violence is a violation of Article 21.",
        "facts": "D.K. Basu wrote a letter to the Chief Justice highlighting the growing incidence of custodial deaths and police torture. The Supreme Court treated the letter as a writ petition.",
        "issues": "What safeguards are needed to prevent custodial violence? What procedures must police follow during arrest and detention?",
        "legal_reasoning": "The Court held that custodial torture is the worst form of violation of Article 21. The right to life includes the right not to be tortured. Police must follow strict procedures during arrest to prevent abuse of power.",
        "key_principles": "11 binding guidelines for arrest procedures; Right against custodial torture under Article 21; Memo of arrest mandatory; Relatives must be informed of arrest; Medical examination of arrested person; Right to consult a lawyer during detention; Magistrate must inquire into custodial injuries",
        "statutes_referenced": "Constitution of India — Article 21, Article 22; CrPC — Sections 41, 50, 54, 56, 57; International Covenant on Civil and Political Rights",
        "precedents_cited": "Nilabati Behera v. State of Orissa (1993); Joginder Kumar v. State of UP (1994)",
        "impact": "Transformed arrest procedures across India. The D.K. Basu guidelines are mandatory for every police force. Foundational for human rights protection in custody. Cited globally in anti-torture jurisprudence.",
        "tags": "criminal,custodial torture,arrest guidelines,police reform,article 21,human rights,indian law,landmark",
    },
    # ── Property & Land Law ────────────────────────────────────────
    {
        "case_name": "Olga Tellis v. Bombay Municipal Corporation",
        "case_number": "AIR 1986 SC 180",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1985,
        "date_decided": date(1985, 7, 10),
        "jurisdiction": "India",
        "judges": "Chief Justice Y.V. Chandrachud, Justice Fazal Ali, Justice Varadarajan",
        "petitioner": "Olga Tellis & Others (pavement dwellers)",
        "respondent": "Bombay Municipal Corporation",
        "outcome": "partial",
        "summary": "Recognized that the right to livelihood is part of the right to life under Article 21. Pavement dwellers cannot be evicted without following due process. However, the eviction itself was not unconstitutional — only the procedure must be just and humane.",
        "facts": "The Bombay Municipal Corporation ordered mass eviction of pavement and slum dwellers. Journalist Olga Tellis and others challenged the evictions arguing that demolishing their shelters would destroy their livelihood.",
        "issues": "Does the right to life under Article 21 include the right to livelihood? Can pavement dwellers be evicted without due process?",
        "legal_reasoning": "The Court held that the right to livelihood is an integral part of the right to life. Deprive a person of their livelihood and you deprive them of life. However, this right is not absolute — the state can evict if it follows fair procedure, gives notice, and provides rehabilitation alternatives.",
        "key_principles": "Right to livelihood under Article 21; Due process required for eviction; No person can be deprived of livelihood without procedure established by law; Humane treatment of displaced persons; Balance between public interest and individual rights",
        "statutes_referenced": "Constitution of India — Article 21, Article 19(1)(e), (g); Bombay Municipal Corporation Act — Section 314",
        "precedents_cited": "Maneka Gandhi v. Union of India (1978); Francis Coralie Mullin v. Administrator, Union Territory of Delhi (1981)",
        "impact": "Expanded Article 21 to include right to livelihood. Foundation for housing rights, rehabilitation policies, and slum dweller protections across India.",
        "tags": "constitutional,right to livelihood,article 21,eviction,housing rights,pavement dwellers,indian law,landmark",
    },
    # ── Environmental Law ──────────────────────────────────────────
    {
        "case_name": "M.C. Mehta v. Union of India (Oleum Gas Leak)",
        "case_number": "AIR 1987 SC 1086",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Environmental",
        "year": 1987,
        "date_decided": date(1987, 2, 17),
        "jurisdiction": "India",
        "judges": "Chief Justice P.N. Bhagwati, Justice Ranganath Misra, Justice G.L. Oza",
        "petitioner": "M.C. Mehta (Environmental Activist)",
        "respondent": "Union of India & Shriram Industries",
        "outcome": "favor",
        "summary": "Established the 'absolute liability' principle for hazardous industries in India — stricter than the UK's Rylands v. Fletcher rule. An enterprise engaged in inherently dangerous activity owes an absolute duty to the community to ensure no harm, and no defenses are available.",
        "facts": "Oleum gas leaked from Shriram Industries' plant in Delhi, causing injury and death. This came shortly after the Bhopal gas tragedy. M.C. Mehta filed a PIL seeking closure of hazardous industries in residential areas.",
        "issues": "What standard of liability applies to hazardous industries? Should Rylands v. Fletcher (strict liability with exceptions) apply, or should India evolve its own standard?",
        "legal_reasoning": "Justice Bhagwati held that India need not follow the 19th century Rylands v. Fletcher rule. A modern, developing country must develop its own jurisprudence. The 'absolute liability' principle means: if an enterprise is engaged in inherently dangerous activity and harm results, the enterprise is absolutely liable — no defenses of act of God, sabotage, or consent are available. The larger the enterprise, the greater the compensation.",
        "key_principles": "Absolute liability (stricter than strict liability); No defenses available for hazardous industries; Polluter pays principle; Larger enterprise = greater compensation; India can develop its own jurisprudence, not bound by English law",
        "statutes_referenced": "Constitution of India — Article 21, Article 48A, Article 51A(g); Environment Protection Act, 1986",
        "precedents_cited": "Rylands v. Fletcher (1868) — distinguished and enhanced; Union Carbide Corporation v. Union of India (Bhopal case)",
        "impact": "Created the absolute liability doctrine unique to Indian law. Foundation of environmental liability law in India. Influenced the Environment Protection Act. Referenced globally as a progressive environmental standard.",
        "tags": "environmental,absolute liability,pollution,hazardous industry,article 21,polluter pays,indian law,landmark",
    },
    {
        "case_name": "M.C. Mehta v. Union of India (Ganga Pollution)",
        "case_number": "AIR 1988 SC 1037",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Environmental",
        "year": 1988,
        "date_decided": date(1988, 1, 12),
        "jurisdiction": "India",
        "judges": "Justice E.S. Venkataramiah, Justice K.N. Singh",
        "petitioner": "M.C. Mehta",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Ordered closure of polluting tanneries along the Ganges. Established that the right to a clean environment is part of the right to life under Article 21. Industries cannot discharge effluents into rivers.",
        "facts": "M.C. Mehta filed a PIL highlighting massive pollution of the River Ganga by tanneries in Kanpur discharging untreated effluents. The Ganga Action Plan had failed to clean the river.",
        "issues": "Can the Court order closure of industries polluting the Ganga? Is the right to a clean environment a fundamental right?",
        "legal_reasoning": "The Court held that the right to live in a healthy environment is part of Article 21. Financial loss from closing polluting industries is secondary to the right of people to live in a pollution-free environment. The polluter pays principle applies — industries must install effluent treatment plants or shut down.",
        "key_principles": "Right to clean environment under Article 21; Polluter pays principle; Court can order industry closure for environmental protection; Environmental protection over economic interest; Public trust doctrine in environmental law",
        "statutes_referenced": "Constitution of India — Article 21, Article 48A; Water (Prevention and Control of Pollution) Act, 1974; Environment Protection Act, 1986",
        "precedents_cited": "M.C. Mehta v. Union of India (Oleum Gas Leak, 1987); Rural Litigation and Entitlement Kendra v. State of UP (1985)",
        "impact": "Led to closure of hundreds of polluting units. Strengthened environmental enforcement. Established that Article 21 includes the right to clean water and environment. Foundation for all subsequent environmental PILs.",
        "tags": "environmental,ganga pollution,right to clean environment,article 21,polluter pays,tanneries,indian law,landmark",
    },
    # ── Women's Rights & Family Law ────────────────────────────────
    {
        "case_name": "Shah Bano Begum v. Mohammed Ahmed Khan",
        "case_number": "AIR 1985 SC 945",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Family",
        "year": 1985,
        "date_decided": date(1985, 4, 23),
        "jurisdiction": "India",
        "judges": "Chief Justice Y.V. Chandrachud",
        "petitioner": "Mohd. Ahmed Khan",
        "respondent": "Shah Bano Begum",
        "outcome": "favor",
        "summary": "Held that a divorced Muslim woman is entitled to maintenance from her former husband under Section 125 CrPC even after the iddat period, if she has not remarried and cannot maintain herself. Sparked a massive national debate on uniform civil code.",
        "facts": "Shah Bano, a 62-year-old Muslim woman, was divorced by her husband through triple talaq after 43 years of marriage. She filed for maintenance under Section 125 CrPC. Her husband argued Muslim personal law only requires maintenance during iddat (3 months).",
        "issues": "Does Section 125 CrPC apply to Muslim women? Is a Muslim woman entitled to maintenance beyond the iddat period?",
        "legal_reasoning": "The Court held that Section 125 CrPC is a secular law applicable to all citizens regardless of religion. The provision was enacted to prevent vagrancy and destitution. A divorced woman who cannot maintain herself is entitled to maintenance. The Court also called for a uniform civil code under Article 44.",
        "key_principles": "Section 125 CrPC applies to all religions; Right to maintenance is secular; Divorced women entitled to maintenance if unable to support themselves; Called for Uniform Civil Code; Personal law cannot override statutory law protecting destitute women",
        "statutes_referenced": "Code of Criminal Procedure — Section 125; Constitution of India — Article 44 (Uniform Civil Code); Muslim Women (Protection of Rights on Divorce) Act, 1986 — enacted as response",
        "precedents_cited": "Bai Tahira v. Ali Hussain (1979)",
        "impact": "Most politically significant judgment in Indian legal history. Led to the Muslim Women (Protection of Rights on Divorce) Act, 1986. Reignited the Uniform Civil Code debate. Eventually influenced the Supreme Court's 2017 triple talaq verdict.",
        "tags": "family,maintenance,muslim personal law,uniform civil code,women's rights,section 125,divorce,indian law,landmark",
    },
    {
        "case_name": "Shayara Bano v. Union of India (Triple Talaq)",
        "case_number": "(2017) 9 SCC 1",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Family",
        "year": 2017,
        "date_decided": date(2017, 8, 22),
        "jurisdiction": "India",
        "judges": "Chief Justice Khehar, Justices Kurian Joseph, Nariman, Abdul Nazeer, Lalit; 5-judge bench; 3-2 decision",
        "petitioner": "Shayara Bano",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Declared instant triple talaq (talaq-e-biddat) unconstitutional and void. A landmark for Muslim women's rights in India, holding that this practice violates Article 14 (equality) as it is manifestly arbitrary.",
        "facts": "Shayara Bano was divorced by her husband via triple talaq communicated through a letter. She challenged the practice as unconstitutional, violating Articles 14, 15, 21, and 25.",
        "issues": "Is the practice of instant triple talaq (talaq-e-biddat) constitutionally valid? Does it violate fundamental rights?",
        "legal_reasoning": "Justice Nariman (for the majority) held that triple talaq is manifestly arbitrary — it allows a husband to break the marriage whimsically without any attempt at reconciliation. What is bad in theology cannot be good in law. The practice is not an essential religious practice deserving protection under Article 25.",
        "key_principles": "Triple talaq is unconstitutional as manifestly arbitrary; Not an essential religious practice; Gender equality in personal law; What is bad in theology is bad in law; Article 14 test of arbitrariness applies to personal law practices",
        "statutes_referenced": "Constitution of India — Articles 14, 15, 21, 25; Muslim Personal Law (Shariat) Application Act, 1937; Muslim Women (Protection of Rights on Marriage) Act, 2019 — enacted post judgment",
        "precedents_cited": "Shah Bano case (1985); Shamim Ara v. State of UP (2002); Danial Latifi v. Union of India (2001)",
        "impact": "Led to the criminalization of triple talaq through the Muslim Women (Protection of Rights on Marriage) Act, 2019. Major advancement for gender justice in personal law.",
        "tags": "family,triple talaq,muslim women,gender equality,article 14,personal law,constitutional,indian law,landmark",
    },
    # ── Labor & Social Justice ─────────────────────────────────────
    {
        "case_name": "Bandhua Mukti Morcha v. Union of India",
        "case_number": "AIR 1984 SC 802",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Labor",
        "year": 1984,
        "date_decided": date(1984, 12, 16),
        "jurisdiction": "India",
        "judges": "Justice P.N. Bhagwati",
        "petitioner": "Bandhua Mukti Morcha (Bonded Labour Liberation Front)",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Landmark PIL on bonded labor. Expanded locus standi by allowing any public-spirited person to file PIL on behalf of disadvantaged groups. Held that the right to live with dignity includes freedom from bonded labor.",
        "facts": "Bandhua Mukti Morcha, an NGO, wrote to the Supreme Court about bonded laborers working in stone quarries in Haryana under inhuman conditions. The Court treated the letter as a writ petition.",
        "issues": "Can an organization file a PIL on behalf of bonded laborers? What are the State's obligations under the Bonded Labour System (Abolition) Act?",
        "legal_reasoning": "Justice Bhagwati expanded the scope of PIL — any person acting bona fide can approach the Court on behalf of those who cannot access justice due to poverty or social disadvantage. The right to live with dignity under Article 21 means freedom from exploitation and bonded labor. The State has a positive obligation to identify, release, and rehabilitate bonded laborers.",
        "key_principles": "Expanded PIL locus standi; Right to live with dignity under Article 21; Bonded labor violates Article 23; State must proactively identify and release bonded laborers; Epistolary jurisdiction — letter treated as petition",
        "statutes_referenced": "Constitution of India — Articles 21, 23, 24; Bonded Labour System (Abolition) Act, 1976; Mines Act, 1952",
        "precedents_cited": "People's Union for Democratic Rights v. Union of India (1982) — Asiad Workers case; Hussainara Khatoon v. Home Secretary (1979)",
        "impact": "Strengthened PIL jurisprudence. Led to identification and release of bonded laborers across India. Established that economic exploitation violates fundamental rights. Template for social justice litigation.",
        "tags": "labor,bonded labor,PIL,article 21,article 23,social justice,exploitation,epistolary jurisdiction,indian law,landmark",
    },
    {
        "case_name": "Indra Sawhney v. Union of India (Mandal Commission)",
        "case_number": "AIR 1993 SC 477",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1992,
        "date_decided": date(1992, 11, 16),
        "jurisdiction": "India",
        "judges": "9-judge bench; Justice B.P. Jeevan Reddy, Justice M.H. Kania, Justice Ahmadi; 6-3 decision",
        "petitioner": "Indra Sawhney",
        "respondent": "Union of India",
        "outcome": "partial",
        "summary": "Upheld the constitutional validity of 27% OBC reservations recommended by the Mandal Commission but imposed a 50% ceiling on total reservations. Excluded the 'creamy layer' of OBCs from reservation benefits.",
        "facts": "The V.P. Singh government implemented the Mandal Commission report providing 27% reservation for Other Backward Classes (OBCs) in government jobs. This was challenged as violating Article 14 and 16.",
        "issues": "Is the 27% OBC reservation constitutional? What is the maximum limit of reservations? Should the economically advanced within OBCs ('creamy layer') be excluded?",
        "legal_reasoning": "The Court upheld OBC reservations as a valid exercise of Article 16(4) but imposed a 50% ceiling on total reservations (SC+ST+OBC combined). The 'creamy layer' — economically advanced OBCs — must be excluded as they do not need reservation. Reservations should not compromise the efficiency of administration (Article 335).",
        "key_principles": "50% ceiling on total reservations; Creamy layer exclusion for OBCs; Reservations under Article 16(4) are an exception, not rule; Backwardness determined by caste + other factors; No reservations in promotions (later modified by 77th Amendment)",
        "statutes_referenced": "Constitution of India — Articles 14, 15(4), 16(4), 335, 340; Mandal Commission Report",
        "precedents_cited": "M.R. Balaji v. State of Mysore (1963); State of Kerala v. N.M. Thomas (1976)",
        "impact": "Definitive ruling on reservations in India. The 50% ceiling and creamy layer principles remain central to Indian reservation policy. Transformed Indian social policy and politics.",
        "tags": "constitutional,reservations,OBC,mandal commission,creamy layer,equality,article 16,social justice,indian law,landmark",
    },
    # ── Administrative Law ─────────────────────────────────────────
    {
        "case_name": "A.K. Kraipak v. Union of India",
        "case_number": "AIR 1970 SC 150",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Administrative",
        "year": 1970,
        "date_decided": date(1970, 1, 29),
        "jurisdiction": "India",
        "judges": "Justice K.S. Hegde",
        "petitioner": "A.K. Kraipak & Others",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Extended principles of natural justice to administrative actions, not just quasi-judicial functions. Held that the dividing line between quasi-judicial and administrative functions is thin, and natural justice must apply to both.",
        "facts": "IFS officers challenged their selection process where the Acting Chief Conservator of Forests was both a member of the selection board and a candidate for selection. This violated the rule against bias.",
        "issues": "Do principles of natural justice apply to administrative functions? Does the participation of a biased member vitiate the selection process?",
        "legal_reasoning": "The Court held that the distinction between quasi-judicial and administrative functions is largely irrelevant — principles of natural justice apply to both. No person should be judge in their own cause (nemo judex in causa sua). The participation of a biased member on the selection board invalidated the entire process.",
        "key_principles": "Natural justice applies to administrative actions; No person can be judge in their own cause; Bias vitiates selection process; Administrative decisions must be fair and reasonable; Rule against bias (nemo judex)",
        "statutes_referenced": "Constitution of India — Article 14, Article 311; Indian Forest Service Rules",
        "precedents_cited": "Ridge v. Baldwin (1964); Province of Bombay v. Kushaldas Advani (1950)",
        "impact": "Extended natural justice to all government decision-making. Foundation of Indian administrative law. Every government selection, inquiry, and disciplinary process must now follow natural justice.",
        "tags": "administrative,natural justice,bias,selection process,rule of law,article 14,indian law,landmark",
    },
    # ── Right to Education ─────────────────────────────────────────
    {
        "case_name": "Mohini Jain v. State of Karnataka",
        "case_number": "AIR 1992 SC 1858",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1992,
        "date_decided": date(1992, 7, 30),
        "jurisdiction": "India",
        "judges": "Justice Kuldip Singh, Justice R.M. Sahai",
        "petitioner": "Mohini Jain",
        "respondent": "State of Karnataka",
        "outcome": "favor",
        "summary": "Declared that the right to education is a fundamental right flowing from Article 21. Capitation fees charged by private medical colleges are unconstitutional as they deny equal access to education.",
        "facts": "Mohini Jain was denied admission to a private medical college in Karnataka because she could not pay the capitation fee of Rs. 60,000. She challenged the practice of charging capitation fees.",
        "issues": "Is the right to education a fundamental right? Are capitation fees by private colleges unconstitutional?",
        "legal_reasoning": "The Court held that the right to education at all levels is a fundamental right under Article 21. Without education, the right to life cannot be enjoyed meaningfully. Capitation fees are arbitrary, violate Article 14, and create inequality in access to education.",
        "key_principles": "Right to education is a fundamental right under Article 21; Capitation fees are unconstitutional; Education essential for dignified life; Commercialization of education violates equality; State must ensure accessible education",
        "statutes_referenced": "Constitution of India — Articles 14, 21, 41, 45; Karnataka Educational Institutions (Prohibition of Capitation Fee) Act",
        "precedents_cited": "Maneka Gandhi v. Union of India (1978); Bandhua Mukti Morcha v. Union of India (1984)",
        "impact": "Led to the right to education being explicitly added as Article 21A through the 86th Constitutional Amendment (2002) and the Right of Children to Free and Compulsory Education Act, 2009.",
        "tags": "constitutional,right to education,article 21,capitation fees,fundamental rights,education,indian law,landmark",
    },
    {
        "case_name": "Unni Krishnan v. State of Andhra Pradesh",
        "case_number": "AIR 1993 SC 2178",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1993,
        "date_decided": date(1993, 2, 4),
        "jurisdiction": "India",
        "judges": "Justice Jeevan Reddy, Justice Mohan, Justice Ahmadi, Justice Bharucha, Justice S.P. Barucha",
        "petitioner": "Unni Krishnan J.P.",
        "respondent": "State of Andhra Pradesh",
        "outcome": "partial",
        "summary": "Affirmed that right to education is a fundamental right under Article 21 but limited it to primary education (up to age 14). Higher education is subject to economic capacity of the state. Created a scheme for private educational institutions.",
        "facts": "Multiple petitions challenged the commercialization of education by private professional colleges charging capitation fees. The Court was asked to define the scope of the right to education.",
        "issues": "What is the scope of the fundamental right to education? Up to what level is education a fundamental right?",
        "legal_reasoning": "The Court held that every citizen has a fundamental right to free education until age 14. Beyond that, education is a right subject to the State's economic capacity. Private institutions receiving state aid must follow fair admission procedures and fee structures.",
        "key_principles": "Right to education up to age 14 is a fundamental right; Beyond 14, right limited by state's economic capacity; Private colleges must follow fair admission norms; Education cannot be fully commercialized; Directive Principles read with Article 21",
        "statutes_referenced": "Constitution of India — Articles 21, 41, 45, 46; 86th Constitutional Amendment (2002); Right of Children to Free and Compulsory Education Act, 2009",
        "precedents_cited": "Mohini Jain v. State of Karnataka (1992) — partially overruled",
        "impact": "Directly led to Article 21A (right to education as explicit fundamental right) and the RTE Act, 2009. Created the framework for regulation of private educational institutions.",
        "tags": "constitutional,right to education,article 21,private colleges,fundamental rights,education,indian law,landmark",
    },
    # ── Corporate / Economic Law ───────────────────────────────────
    {
        "case_name": "Vodafone International Holdings v. Union of India",
        "case_number": "(2012) 6 SCC 613",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Tax",
        "year": 2012,
        "date_decided": date(2012, 1, 20),
        "jurisdiction": "India",
        "judges": "Chief Justice S.H. Kapadia, Justice K.S. Radhakrishnan, Justice Swatanter Kumar",
        "petitioner": "Vodafone International Holdings BV",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Ruled that Vodafone was not liable to pay capital gains tax on its acquisition of Hutchison's Indian telecom business through an offshore transaction. The transfer of shares between two foreign companies fell outside Indian tax jurisdiction.",
        "facts": "Vodafone acquired Hutchison's 67% stake in its Indian mobile business for $11.2 billion through a transaction between companies in the Cayman Islands and the Netherlands. The Indian government demanded Rs. 11,000 crore in capital gains tax.",
        "issues": "Does India have jurisdiction to tax an offshore transfer of shares between two foreign entities where the underlying assets are in India?",
        "legal_reasoning": "The Court held that the transaction was a transfer of shares of a Cayman Islands company, and India did not have jurisdiction to tax an offshore transaction. The 'look at' test should be applied, not the 'look through' approach. The Revenue cannot look beyond the legal structure to tax an indirect transfer.",
        "key_principles": "Offshore share transfers not taxable in India; Look at vs. look through doctrine; Tax jurisdiction limited to territorial boundaries; Foreign investment structures are legitimate; Retrospective taxation is impermissible",
        "statutes_referenced": "Income Tax Act, 1961 — Sections 9, 195; Finance Act, 2012 (retrospective amendment); India-Netherlands DTAA",
        "precedents_cited": "Azadi Bachao Andolan v. Union of India (2003); McDowell & Co. v. CTO (1985)",
        "impact": "Led to India's controversial retrospective tax amendment in Finance Act 2012. Eventually India repealed the retrospective tax in 2021 after international arbitration loss. Shaped India's tax policy for foreign investment.",
        "tags": "tax,capital gains,foreign investment,vodafone,offshore transaction,retrospective taxation,indian law,landmark",
    },
    # ── Freedom of Speech & Media ──────────────────────────────────
    {
        "case_name": "Shreya Singhal v. Union of India",
        "case_number": "AIR 2015 SC 1523",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 2015,
        "date_decided": date(2015, 3, 24),
        "jurisdiction": "India",
        "judges": "Justice J. Chelameswar, Justice R.F. Nariman",
        "petitioner": "Shreya Singhal",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Struck down Section 66A of the Information Technology Act as unconstitutional for violating freedom of speech under Article 19(1)(a). The provision was vague, overbroad, and had a chilling effect on free speech online.",
        "facts": "Two young women were arrested in Mumbai for posting a Facebook comment criticizing the shutdown of the city for a political leader's funeral. Shreya Singhal, a law student, challenged Section 66A which criminalized 'offensive' online messages.",
        "issues": "Does Section 66A of the IT Act violate Article 19(1)(a) freedom of speech? Is the provision unconstitutionally vague?",
        "legal_reasoning": "Justice Nariman held that Section 66A was vague and overbroad. Terms like 'grossly offensive,' 'menacing,' and 'causing annoyance' had no clear definition. The provision created a chilling effect on free speech. It failed the tests under Article 19(2) — the restrictions were not in the interest of any ground listed in Article 19(2).",
        "key_principles": "Online speech has same protection as offline speech; Vague and overbroad laws violate Article 19(1)(a); Chilling effect doctrine; Section 66A struck down entirely; Distinction between discussion, advocacy, and incitement",
        "statutes_referenced": "Information Technology Act, 2000 — Section 66A (struck down), Section 69A, Section 79; Constitution of India — Article 19(1)(a), Article 19(2)",
        "precedents_cited": "Romesh Thappar v. State of Madras (1950); S. Rangarajan v. P. Jagjivan Ram (1989)",
        "impact": "Landmark for digital free speech in India and globally. Struck down one of the most misused provisions of Indian law. Established that online expression is constitutionally protected. Cited in free speech cases worldwide.",
        "tags": "constitutional,free speech,internet freedom,section 66A,article 19,IT act,digital rights,online speech,indian law,landmark",
    },
    # ── Election Law ───────────────────────────────────────────────
    {
        "case_name": "People's Union for Civil Liberties (PUCL) v. Union of India (NOTA)",
        "case_number": "(2013) 10 SCC 1",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 2013,
        "date_decided": date(2013, 9, 27),
        "jurisdiction": "India",
        "judges": "Chief Justice P. Sathasivam, Justice Ranjana Prakash Desai, Justice Ranjan Gogoi",
        "petitioner": "People's Union for Civil Liberties (PUCL)",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Directed the Election Commission to provide a 'None of the Above' (NOTA) button on EVMs, giving voters the right to reject all candidates while maintaining ballot secrecy. A negative vote is part of the right to freedom of expression.",
        "facts": "PUCL filed a PIL arguing that voters should have the option to reject all candidates in an election. Under the existing system, voters could only choose among listed candidates, with no way to express dissatisfaction with all options.",
        "issues": "Do voters have a fundamental right to reject all candidates? Should a NOTA option be available on electronic voting machines?",
        "legal_reasoning": "The Court held that the right to vote includes the right not to vote for any candidate. NOTA empowers voters and protects their freedom of expression under Article 19(1)(a). Secret ballot is a key feature of free elections — the existing system of Form 49-O required voters to reveal their identity, violating secrecy.",
        "key_principles": "Right to reject all candidates (NOTA); Negative voting as freedom of expression; Secret ballot protection; Democracy requires informed and empowered voters; Electoral reforms through judicial intervention",
        "statutes_referenced": "Constitution of India — Article 19(1)(a), Article 324; Representation of the People Act, 1951 — Section 49-O; Conduct of Elections Rules, 1961",
        "precedents_cited": "Union of India v. Association for Democratic Reforms (2002); PUCL v. Union of India (2003)",
        "impact": "NOTA was introduced in all elections from 2013 onwards. India became one of the few democracies with a formal NOTA option. Empowered millions of voters to express dissent within the democratic framework.",
        "tags": "constitutional,election law,NOTA,voting rights,freedom of expression,article 19,democracy,electoral reform,indian law,landmark",
    },
    # ── PIL & Access to Justice ────────────────────────────────────
    {
        "case_name": "S.P. Gupta v. Union of India (Judges Transfer Case I)",
        "case_number": "AIR 1982 SC 149",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1981,
        "date_decided": date(1981, 12, 30),
        "jurisdiction": "India",
        "judges": "7-judge bench; Justice P.N. Bhagwati",
        "petitioner": "S.P. Gupta",
        "respondent": "Union of India",
        "outcome": "partial",
        "summary": "Foundational case for Public Interest Litigation (PIL) in India. Liberalized locus standi so that any member of the public acting bona fide can approach the Court for enforcement of fundamental rights of disadvantaged groups.",
        "facts": "S.P. Gupta challenged the government's transfer and non-appointment of High Court judges. The broader issue was whether citizens could challenge government actions affecting the judiciary.",
        "issues": "Can any public-spirited citizen file a petition on behalf of others? What is the scope of judicial review of executive action regarding judicial appointments?",
        "legal_reasoning": "Justice Bhagwati held that where a legal wrong is caused to a class of persons who cannot approach the Court due to poverty, illiteracy, or social disadvantage, any member of the public acting bona fide can file a petition. Access to justice is a fundamental right. The Court should not insist on the petitioner being personally aggrieved.",
        "key_principles": "Liberalized locus standi for PIL; Any bona fide person can file PIL; Access to justice as a fundamental right; Judicial activism for social justice; Court as protector of fundamental rights of the disadvantaged",
        "statutes_referenced": "Constitution of India — Articles 21, 32, 226; Legal Services Authorities Act (subsequent)",
        "precedents_cited": "Municipal Council, Ratlam v. Vardhichand (1980); Fertilizer Corporation Kamgar Union v. Union of India (1981)",
        "impact": "Birth of PIL movement in India — one of India's greatest contributions to world jurisprudence. Opened the courts to the poor and marginalized. Led to thousands of PILs on environment, education, labor rights, and governance.",
        "tags": "constitutional,PIL,public interest litigation,locus standi,access to justice,judicial activism,article 32,indian law,landmark",
    },
    # ── Right to Information ───────────────────────────────────────
    {
        "case_name": "S.P. Gupta v. Union of India (Right to Know)",
        "case_number": "AIR 1982 SC 149",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Constitutional",
        "year": 1982,
        "date_decided": date(1982, 1, 15),
        "jurisdiction": "India",
        "judges": "Justice P.N. Bhagwati, 7-judge bench",
        "petitioner": "S.P. Gupta",
        "respondent": "Union of India",
        "outcome": "favor",
        "summary": "Established that the right to know is implicit in the right to free speech under Article 19(1)(a). Open government is the foundation of democracy. Government actions must be transparent.",
        "facts": "In the context of the Judges Transfer case, the Court examined whether government correspondence regarding judicial appointments could be kept secret from the public.",
        "issues": "Does the public have a right to access government information? Is the right to know a fundamental right?",
        "legal_reasoning": "Justice Bhagwati held that the concept of open government is the direct emanation from the right to know, which is implicit in Article 19(1)(a). In a democracy, people are the masters and have a right to know how their government functions. Disclosure of information is the rule — secrecy the exception.",
        "key_principles": "Right to know is a fundamental right under Article 19(1)(a); Open government in democracy; Disclosure is the rule, secrecy the exception; Government transparency is essential for accountability; Citizens' right to information",
        "statutes_referenced": "Constitution of India — Article 19(1)(a); Right to Information Act, 2005 — enacted subsequently",
        "precedents_cited": "State of UP v. Raj Narain (1975); Bennett Coleman & Co. v. Union of India (1973)",
        "impact": "Laid the constitutional foundation for the Right to Information Act, 2005. Transformed governance accountability in India. The RTI Act has become one of India's most powerful anti-corruption tools.",
        "tags": "constitutional,right to information,RTI,free speech,article 19,transparency,open government,indian law,landmark",
    },
    # ── Arbitration & Commercial Law ───────────────────────────────
    {
        "case_name": "BALCO v. Kaiser Aluminium (Bharat Aluminium Co.)",
        "case_number": "(2012) 9 SCC 552",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Corporate",
        "year": 2012,
        "date_decided": date(2012, 9, 6),
        "jurisdiction": "India",
        "judges": "Chief Justice S.H. Kapadia, 5-judge bench",
        "petitioner": "Bharat Aluminium Co. (BALCO)",
        "respondent": "Kaiser Aluminium Technical Services Inc.",
        "outcome": "partial",
        "summary": "Overruled the 'Bhatia International' principle and held that Part I of the Arbitration Act does not apply to foreign-seated arbitrations. Indian courts have no jurisdiction to interfere with arbitrations seated outside India.",
        "facts": "BALCO and Kaiser had an agreement with arbitration seated in London. BALCO sought interim measures from Indian courts under Section 9 of the Arbitration Act. The question was whether Indian courts could intervene in foreign-seated arbitrations.",
        "issues": "Does Part I of the Arbitration and Conciliation Act, 1996 apply to arbitrations seated outside India?",
        "legal_reasoning": "The Court held that the seat of arbitration determines jurisdiction. Part I applies only to arbitrations seated in India. Indian courts cannot exercise supervisory jurisdiction over foreign-seated arbitrations. This respects international arbitration principles and party autonomy.",
        "key_principles": "Seat theory determines arbitration jurisdiction; Part I does not apply to foreign-seated arbitrations; Party autonomy in choosing seat; Indian courts cannot interfere with foreign arbitrations; Pro-arbitration judicial approach",
        "statutes_referenced": "Arbitration and Conciliation Act, 1996 — Sections 2, 9, 34; UNCITRAL Model Law",
        "precedents_cited": "Bhatia International v. Bulk Trading (2002) — overruled; Venture Global Engineering v. Satyam (2008) — overruled",
        "impact": "Made India more arbitration-friendly. Aligned Indian law with international arbitration standards. Boosted India's reputation as an arbitration-supportive jurisdiction.",
        "tags": "corporate,arbitration,international arbitration,seat theory,commercial law,BALCO,indian law,landmark",
    },
    # ── Information Technology & Intermediary Liability ─────────────
    {
        "case_name": "Google India Pvt. Ltd. v. Visakha Industries",
        "case_number": "(2020) 4 SCC 162",
        "court": "Supreme Court of India",
        "court_level": "supreme",
        "case_type": "Civil",
        "year": 2020,
        "date_decided": date(2020, 1, 14),
        "jurisdiction": "India",
        "judges": "Justice Ashok Bhushan, Justice R. Subhash Reddy, Justice M.R. Shah",
        "petitioner": "Google India Pvt. Ltd.",
        "respondent": "Visakha Industries",
        "outcome": "partial",
        "summary": "Clarified the intermediary liability framework under Section 79 of the IT Act. Held that intermediaries like Google are entitled to safe harbor protection when they comply with due diligence requirements and act on receiving actual knowledge of unlawful content.",
        "facts": "Visakha Industries alleged that defamatory content was published on Google's platforms and sought to hold Google directly liable. Google claimed intermediary protection under Section 79 of the IT Act.",
        "issues": "What is the scope of safe harbor protection for internet intermediaries? When does an intermediary lose its protection?",
        "legal_reasoning": "The Court held that intermediaries enjoy safe harbor under Section 79 when they act as mere platforms without modifying third-party content. Protection is lost when the intermediary has actual knowledge of unlawful content and fails to act. The Shreya Singhal guidelines on court orders for content removal must be followed.",
        "key_principles": "Safe harbor for intermediaries under Section 79; Actual knowledge standard for liability; Intermediaries must act on court orders; Due diligence requirements for platforms; Balance between free speech and content regulation",
        "statutes_referenced": "Information Technology Act, 2000 — Sections 79, 69A; IT Intermediary Guidelines Rules, 2011",
        "precedents_cited": "Shreya Singhal v. Union of India (2015); Myspace Inc. v. Super Cassettes (2017)",
        "impact": "Clarified the liability framework for tech companies operating in India. Important for platform regulation and content moderation policies.",
        "tags": "civil,intermediary liability,internet law,IT act,safe harbor,section 79,technology,indian law,landmark",
    },
]
