// ─── India IT Rules 2026 — AI Content Labeling Rules (Codified) ─────────────
//
// Based on: Information Technology (Intermediary Guidelines and Digital Media
// Ethics Code) Amendment Rules, 2026
//
// These rules mandate that AI-generated or significantly AI-modified content
// must be labeled, carry metadata, and platforms must proactively detect such
// content. This file codifies every checkable rule into machine-readable form.
// ─────────────────────────────────────────────────────────────────────────────

export interface ComplianceRule {
  id: string;
  name: string;
  section: string;
  description: string;
  checkType: 'label' | 'metadata' | 'disclosure' | 'platform' | 'exemption';
  severity: 'critical' | 'major' | 'minor' | 'info';
  appliesTo: ('image' | 'video' | 'audio' | 'text')[];
  exemptions: string[];
}

// ─── Rule Definitions ────────────────────────────────────────────────────────

export const COMPLIANCE_RULES: ComplianceRule[] = [
  // ── Section 3: Labeling Requirements ─────────────────────────────────────
  {
    id: 'LABEL-001',
    name: 'AI-Generated Content Label',
    section: 'Rule 3(1)(b)(v)',
    description:
      'Content that is entirely generated by an AI system must carry a clear, prominently visible label stating it is AI-generated.',
    checkType: 'label',
    severity: 'critical',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },
  {
    id: 'LABEL-002',
    name: 'AI-Modified Content Label',
    section: 'Rule 3(1)(b)(vi)',
    description:
      'Content that has been substantially modified using AI tools must carry a label indicating the nature and extent of AI modification.',
    checkType: 'label',
    severity: 'critical',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: ['EXEMPT-001', 'EXEMPT-002', 'EXEMPT-003', 'EXEMPT-004'],
  },
  {
    id: 'LABEL-003',
    name: 'Synthetic Media Disclosure',
    section: 'Rule 3(1)(b)(vii)',
    description:
      'Deepfake or synthetic media that depicts a real person must carry a mandatory disclosure that the content is computer-generated and does not represent reality.',
    checkType: 'disclosure',
    severity: 'critical',
    appliesTo: ['image', 'video', 'audio'],
    exemptions: [],
  },
  {
    id: 'LABEL-004',
    name: 'Label Visibility Standard',
    section: 'Rule 3(2)(a)',
    description:
      'AI content labels must be clearly visible, legible, and not removable by the end user. Labels on images must be embedded; labels on video/audio must appear at the start and at regular intervals.',
    checkType: 'label',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },
  {
    id: 'LABEL-005',
    name: 'Label Language Requirement',
    section: 'Rule 3(2)(b)',
    description:
      'Labels must be in English and, where applicable, in the language of the content to ensure accessibility.',
    checkType: 'label',
    severity: 'minor',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },

  // ── Section 4: Metadata Requirements ─────────────────────────────────────
  {
    id: 'META-001',
    name: 'AI Generation Metadata',
    section: 'Rule 4(1)',
    description:
      'AI-generated content must embed machine-readable metadata (e.g., C2PA, IPTC) indicating the AI system, model, and timestamp of generation.',
    checkType: 'metadata',
    severity: 'critical',
    appliesTo: ['image', 'video', 'audio'],
    exemptions: [],
  },
  {
    id: 'META-002',
    name: 'Metadata Integrity',
    section: 'Rule 4(2)',
    description:
      'Platforms must not strip or degrade AI content metadata during upload, processing, or distribution. Original provenance metadata must be preserved.',
    checkType: 'metadata',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio'],
    exemptions: [],
  },
  {
    id: 'META-003',
    name: 'Content Provenance Trail',
    section: 'Rule 4(3)',
    description:
      'A verifiable chain of provenance from creation to publication must be maintained, including the identity of the AI tool and the publisher.',
    checkType: 'metadata',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },

  // ── Section 5: Platform Obligations ──────────────────────────────────────
  {
    id: 'PLAT-001',
    name: 'Proactive AI Detection',
    section: 'Rule 5(1)',
    description:
      'Significant social media intermediaries must deploy technology-based measures to identify AI-generated or manipulated content and apply appropriate labels.',
    checkType: 'platform',
    severity: 'critical',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },
  {
    id: 'PLAT-002',
    name: 'User Reporting Mechanism',
    section: 'Rule 5(2)',
    description:
      'Platforms must provide users a mechanism to flag content they believe is AI-generated but unlabeled.',
    checkType: 'platform',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },
  {
    id: 'PLAT-003',
    name: 'Compliance Reporting',
    section: 'Rule 5(3)',
    description:
      'Platforms must publish periodic compliance reports disclosing the volume of AI content detected, labeled, and actioned upon.',
    checkType: 'platform',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },
  {
    id: 'PLAT-004',
    name: 'Grievance Redressal for AI Content',
    section: 'Rule 5(4)',
    description:
      'The existing grievance officer mechanism must be extended to handle complaints related to AI-generated content, including mislabeling or missing labels.',
    checkType: 'platform',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },

  // ── Section 6: Publisher Obligations ─────────────────────────────────────
  {
    id: 'PUB-001',
    name: 'Publisher Self-Declaration',
    section: 'Rule 6(1)',
    description:
      'Publishers of news and current affairs content must self-declare whether AI tools were used in content creation or modification.',
    checkType: 'disclosure',
    severity: 'critical',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: [],
  },
  {
    id: 'PUB-002',
    name: 'AI Tool Disclosure',
    section: 'Rule 6(2)',
    description:
      'Publishers must disclose the specific AI tool or model used in content creation (e.g., "Generated using ChatGPT", "Image created with DALL-E 3").',
    checkType: 'disclosure',
    severity: 'major',
    appliesTo: ['image', 'video', 'audio', 'text'],
    exemptions: ['EXEMPT-001', 'EXEMPT-002', 'EXEMPT-003'],
  },
];

// ─── Exemptions ──────────────────────────────────────────────────────────────

export interface Exemption {
  id: string;
  name: string;
  section: string;
  description: string;
  examples: string[];
}

export const EXEMPTIONS: Exemption[] = [
  {
    id: 'EXEMPT-001',
    name: 'Minor Technical Adjustments',
    section: 'Rule 7(a)',
    description:
      'Content that has undergone only minor technical adjustments using AI is exempt from labeling requirements.',
    examples: [
      'Color correction and white balance',
      'Cropping and resizing',
      'Noise reduction',
      'Brightness/contrast adjustment',
      'Format conversion',
      'Compression',
    ],
  },
  {
    id: 'EXEMPT-002',
    name: 'Accessibility Modifications',
    section: 'Rule 7(b)',
    description:
      'AI modifications made solely for accessibility purposes are exempt.',
    examples: [
      'Auto-generated closed captions',
      'Audio descriptions for visually impaired',
      'Sign language overlay generation',
      'Text-to-speech conversion for accessibility',
      'Alt text generation',
    ],
  },
  {
    id: 'EXEMPT-003',
    name: 'Language Translation',
    section: 'Rule 7(c)',
    description:
      'AI-powered translation of content from one language to another is exempt, provided the original content is not AI-generated.',
    examples: [
      'Machine translation of articles',
      'Subtitle translation',
      'Real-time interpretation',
    ],
  },
  {
    id: 'EXEMPT-004',
    name: 'Standard Editorial Assistance',
    section: 'Rule 7(d)',
    description:
      'Use of AI for standard editorial tasks like grammar correction, spell-checking, and basic formatting is exempt.',
    examples: [
      'Grammar and spelling correction',
      'Punctuation fixes',
      'Basic formatting and layout',
      'Autocomplete/predictive text',
    ],
  },
];

// ─── Penalty Framework ───────────────────────────────────────────────────────

export interface PenaltyInfo {
  severity: 'critical' | 'major' | 'minor';
  consequence: string;
  timelineToComply: string;
}

export const PENALTY_FRAMEWORK: Record<string, PenaltyInfo> = {
  critical: {
    severity: 'critical',
    consequence:
      'Loss of safe harbor protection under Section 79 of the IT Act. Platform may be treated as publisher and held liable for unlabeled AI content.',
    timelineToComply: '72 hours from notice',
  },
  major: {
    severity: 'major',
    consequence:
      'Formal notice from the Grievance Appellate Committee. Repeated violations may lead to loss of safe harbor.',
    timelineToComply: '15 days from notice',
  },
  minor: {
    severity: 'minor',
    consequence:
      'Advisory notice with recommendation to update processes. No immediate penalty.',
    timelineToComply: '30 days from notice',
  },
};

// ─── Helper: Get rules applicable to a content type ──────────────────────────

export function getRulesForContentType(
  contentType: 'image' | 'video' | 'audio' | 'text'
): ComplianceRule[] {
  return COMPLIANCE_RULES.filter((r) => r.appliesTo.includes(contentType));
}

export function getExemption(id: string): Exemption | undefined {
  return EXEMPTIONS.find((e) => e.id === id);
}

export function getRuleById(id: string): ComplianceRule | undefined {
  return COMPLIANCE_RULES.find((r) => r.id === id);
}
